[tool.poetry]
name = "n100tickers"
version = "0.1.1-alpha.0"
description = "Return NASDAQ 100 ticker symbols by date."
authors = ["Jeff McCarrell <jeff@mccarrell.org>"]

[tool.poetry.dependencies]
python = "^3.8"
pyyaml = "^5.3.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
sphinx = "^3.2.1"
doc2dash = "^2.3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
